on:
  pull_request:
  workflow_dispatch:

jobs:
  version-check:
    name: Check version increment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/validate-bumpversion@main

  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/setup-golang@main
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.26.1
      - name: Install prek
        id: install_prek
        run: |
          pipx install prek
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Do pre-commit checks
        id: prek
        run: |
          prek run --all-files

  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/setup-golang@main
      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@v2.1.0
      - name: Run tests
        run: |
          set -o pipefail
          go test -v ./... 2>&1 | go-junit-report -set-exit-code > gotest.xml
      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: "**/gotest*.xml"
          detailed_summary: true
          check_name: "Go test report"

  publish:
    needs: [version-check, pre-commit, test]
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: traefik
          component: plugin
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
